//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoAwesome.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OctoKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OctoKeys() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoAwesome.Client.Languages.OctoKeys", typeof(OctoKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Backward ähnelt.
        /// </summary>
        internal static string backward {
            get {
                return ResourceManager.GetString("backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEBUG: All Blocktypes in Inventory ähnelt.
        /// </summary>
        internal static string debug_allblocks {
            get {
                return ResourceManager.GetString("debug_allblocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEBUG: Show/Hide Debug Control ähnelt.
        /// </summary>
        internal static string debug_control {
            get {
                return ResourceManager.GetString("debug_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flymode ähnelt.
        /// </summary>
        internal static string flymode {
            get {
                return ResourceManager.GetString("flymode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Forward ähnelt.
        /// </summary>
        internal static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free/Capture Mouse ähnelt.
        /// </summary>
        internal static string freemouse {
            get {
                return ResourceManager.GetString("freemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Full Screen Mode ähnelt.
        /// </summary>
        internal static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head Down ähnelt.
        /// </summary>
        internal static string headdown {
            get {
                return ResourceManager.GetString("headdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head Left ähnelt.
        /// </summary>
        internal static string headleft {
            get {
                return ResourceManager.GetString("headleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head Right ähnelt.
        /// </summary>
        internal static string headright {
            get {
                return ResourceManager.GetString("headright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head Up ähnelt.
        /// </summary>
        internal static string headup {
            get {
                return ResourceManager.GetString("headup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide all Controls ähnelt.
        /// </summary>
        internal static string hidecontrols {
            get {
                return ResourceManager.GetString("hidecontrols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interact ähnelt.
        /// </summary>
        internal static string interact {
            get {
                return ResourceManager.GetString("interact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory ähnelt.
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jump ähnelt.
        /// </summary>
        internal static string jump {
            get {
                return ResourceManager.GetString("jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Left ähnelt.
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Right ähnelt.
        /// </summary>
        internal static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 0 ähnelt.
        /// </summary>
        internal static string slot0 {
            get {
                return ResourceManager.GetString("slot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 1 ähnelt.
        /// </summary>
        internal static string slot1 {
            get {
                return ResourceManager.GetString("slot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 2 ähnelt.
        /// </summary>
        internal static string slot2 {
            get {
                return ResourceManager.GetString("slot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 3 ähnelt.
        /// </summary>
        internal static string slot3 {
            get {
                return ResourceManager.GetString("slot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 4 ähnelt.
        /// </summary>
        internal static string slot4 {
            get {
                return ResourceManager.GetString("slot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 5 ähnelt.
        /// </summary>
        internal static string slot5 {
            get {
                return ResourceManager.GetString("slot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 6 ähnelt.
        /// </summary>
        internal static string slot6 {
            get {
                return ResourceManager.GetString("slot6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 7 ähnelt.
        /// </summary>
        internal static string slot7 {
            get {
                return ResourceManager.GetString("slot7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 8 ähnelt.
        /// </summary>
        internal static string slot8 {
            get {
                return ResourceManager.GetString("slot8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory Slot 9 ähnelt.
        /// </summary>
        internal static string slot9 {
            get {
                return ResourceManager.GetString("slot9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teleport ähnelt.
        /// </summary>
        internal static string teleport {
            get {
                return ResourceManager.GetString("teleport", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die toggle_chat ähnelt.
        /// </summary>
        internal static string toggle_chat
        {
            get
            {
                return ResourceManager.GetString("toggle_chat", resourceCulture);
            }
        }
    }
}
