//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoAwesome.Basics.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OctoBasics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OctoBasics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoAwesome.Basics.Languages.OctoBasics", typeof(OctoBasics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birch Wood.
        /// </summary>
        internal static string BirchWood {
            get {
                return ResourceManager.GetString("BirchWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Cotton.
        /// </summary>
        internal static string BlueCotton {
            get {
                return ResourceManager.GetString("BlueCotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        internal static string Brick {
            get {
                return ResourceManager.GetString("Brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cactus.
        /// </summary>
        internal static string Cactus {
            get {
                return ResourceManager.GetString("Cactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        internal static string Grass {
            get {
                return ResourceManager.GetString("Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        internal static string Gravel {
            get {
                return ResourceManager.GetString("Gravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Cotton.
        /// </summary>
        internal static string GreenCotton {
            get {
                return ResourceManager.GetString("GreenCotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greystone.
        /// </summary>
        internal static string Greystone {
            get {
                return ResourceManager.GetString("Greystone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Ore.
        /// </summary>
        internal static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves.
        /// </summary>
        internal static string Leaves {
            get {
                return ResourceManager.GetString("Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Leaves.
        /// </summary>
        internal static string OrangeLeaves {
            get {
                return ResourceManager.GetString("OrangeLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oven.
        /// </summary>
        internal static string Oven {
            get {
                return ResourceManager.GetString("Oven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plank.
        /// </summary>
        internal static string Plank {
            get {
                return ResourceManager.GetString("Plank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Cotton.
        /// </summary>
        internal static string RedCotton {
            get {
                return ResourceManager.GetString("RedCotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Plank.
        /// </summary>
        internal static string RedPlank {
            get {
                return ResourceManager.GetString("RedPlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redstone.
        /// </summary>
        internal static string Redstone {
            get {
                return ResourceManager.GetString("Redstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        internal static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Brick.
        /// </summary>
        internal static string StoneBrick {
            get {
                return ResourceManager.GetString("StoneBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan Cotton.
        /// </summary>
        internal static string TanCotton {
            get {
                return ResourceManager.GetString("TanCotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        internal static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
