//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoAwesome.Client.UI.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OctoKeys {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OctoKeys() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OctoAwesome.Client.UI.Languages.OctoKeys", typeof(OctoKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        public static string backward {
            get {
                return ResourceManager.GetString("backward", resourceCulture);
            }
        }
        
        public static string debug_allblocks {
            get {
                return ResourceManager.GetString("debug_allblocks", resourceCulture);
            }
        }
        
        public static string debug_allfoods {
            get {
                return ResourceManager.GetString("debug_allfoods", resourceCulture);
            }
        }
        
        public static string debug_allitems {
            get {
                return ResourceManager.GetString("debug_allitems", resourceCulture);
            }
        }
        
        public static string debug_control {
            get {
                return ResourceManager.GetString("debug_control", resourceCulture);
            }
        }
        
        public static string debug_boundingboxes {
            get {
                return ResourceManager.GetString("debug_boundingboxes", resourceCulture);
            }
        }
        
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        public static string flymode {
            get {
                return ResourceManager.GetString("flymode", resourceCulture);
            }
        }
        
        public static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        public static string freemouse {
            get {
                return ResourceManager.GetString("freemouse", resourceCulture);
            }
        }
        
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        public static string headdown {
            get {
                return ResourceManager.GetString("headdown", resourceCulture);
            }
        }
        
        public static string headleft {
            get {
                return ResourceManager.GetString("headleft", resourceCulture);
            }
        }
        
        public static string headright {
            get {
                return ResourceManager.GetString("headright", resourceCulture);
            }
        }
        
        public static string headup {
            get {
                return ResourceManager.GetString("headup", resourceCulture);
            }
        }
        
        public static string hidecontrols {
            get {
                return ResourceManager.GetString("hidecontrols", resourceCulture);
            }
        }
        
        public static string interact {
            get {
                return ResourceManager.GetString("interact", resourceCulture);
            }
        }
        
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        public static string jump {
            get {
                return ResourceManager.GetString("jump", resourceCulture);
            }
        }
        
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        public static string slot0 {
            get {
                return ResourceManager.GetString("slot0", resourceCulture);
            }
        }
        
        public static string slot1 {
            get {
                return ResourceManager.GetString("slot1", resourceCulture);
            }
        }
        
        public static string slot2 {
            get {
                return ResourceManager.GetString("slot2", resourceCulture);
            }
        }
        
        public static string slot3 {
            get {
                return ResourceManager.GetString("slot3", resourceCulture);
            }
        }
        
        public static string slot4 {
            get {
                return ResourceManager.GetString("slot4", resourceCulture);
            }
        }
        
        public static string slot5 {
            get {
                return ResourceManager.GetString("slot5", resourceCulture);
            }
        }
        
        public static string slot6 {
            get {
                return ResourceManager.GetString("slot6", resourceCulture);
            }
        }
        
        public static string slot7 {
            get {
                return ResourceManager.GetString("slot7", resourceCulture);
            }
        }
        
        public static string slot8 {
            get {
                return ResourceManager.GetString("slot8", resourceCulture);
            }
        }
        
        public static string slot9 {
            get {
                return ResourceManager.GetString("slot9", resourceCulture);
            }
        }
        
        public static string teleport {
            get {
                return ResourceManager.GetString("teleport", resourceCulture);
            }
        }
        
        public static string toggle_chat {
            get {
                return ResourceManager.GetString("toggle_chat", resourceCulture);
            }
        }
        
        public static string toggleAmbientOcclusion {
            get {
                return ResourceManager.GetString("toggleAmbientOcclusion", resourceCulture);
            }
        }
        
        public static string toggleWireFrame {
            get {
                return ResourceManager.GetString("toggleWireFrame", resourceCulture);
            }
        }
    }
}
